"""add deleted colum to User, Post, Comment

Revision ID: 0e4550bd802b
Revises: 92da0f1da1a8
Create Date: 2021-02-28 16:16:20.921783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0e4550bd802b"
down_revision = "92da0f1da1a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("deleted", sa.Boolean(), nullable=False, default=False))
    op.add_column("Post", sa.Column("deleted", sa.Boolean(), nullable=False, default=False))
    op.add_column("Comment", sa.Column("deleted", sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "deleted")
    op.drop_column("Post", "deleted")
    op.drop_column("Comment", "deleted")
    # ### end Alembic commands ###
