"""initial commit

Revision ID: a02a9c670610
Revises: 
Create Date: 2021-02-16 23:56:44.199882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a02a9c670610"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_USER_created_at"), "USER", ["created_at"], unique=False)
    op.create_index(op.f("ix_USER_email"), "USER", ["email"], unique=True)
    op.create_table(
        "POST",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_POST_created_at"), "POST", ["created_at"], unique=False)
    op.create_table(
        "COMMENT",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("post_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["POST.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_COMMENT_created_at"), "COMMENT", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_COMMENT_created_at"), table_name="COMMENT")
    op.drop_table("COMMENT")
    op.drop_index(op.f("ix_POST_created_at"), table_name="POST")
    op.drop_table("POST")
    op.drop_index(op.f("ix_USER_email"), table_name="USER")
    op.drop_index(op.f("ix_USER_created_at"), table_name="USER")
    op.drop_table("USER")
    # ### end Alembic commands ###
