"""add USER_COMMENT_LIKE TABLE ( FOR COMMENT LIKE FEATURE )

Revision ID: af72d34a36a2
Revises: cc75db538859
Create Date: 2021-03-01 13:37:01.573101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "af72d34a36a2"
down_revision = "cc75db538859"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER_COMMENT_LIKE",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("comment_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["COMMENT.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id", "comment_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("USER_COMMENT_LIKE")
    # ### end Alembic commands ###
