"""add user.[about_me]

Revision ID: c60b745c0291
Revises: ed0e21821c25
Create Date: 2021-02-27 01:17:54.402270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c60b745c0291"
down_revision = "ed0e21821c25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("abount_me", sa.TEXT, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "abount_me")
    # ### end Alembic commands ###
