"""add USER_POST_LIKE TABLE ( FOR LIKE FEATURE )

Revision ID: cc75db538859
Revises: 0e4550bd802b
Create Date: 2021-02-28 20:37:05.280723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "cc75db538859"
down_revision = "0e4550bd802b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "USER_POST_LIKE",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["POST.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["USER.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id", "post_id"),
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("USER_POST_LIKE")
    # ### end Alembic commands ###
