"""add user.[gender, birth, location, job]

Revision ID: ed0e21821c25
Revises: a02a9c670610
Create Date: 2021-02-27 00:30:51.041082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ed0e21821c25"
down_revision = "a02a9c670610"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("gender", sa.Enum("M", "F", name="gender"), nullable=True)
    )
    op.add_column("User", sa.Column("birth", sa.DateTime, nullable=True))
    op.add_column("User", sa.Column("location", sa.String(length=255), nullable=True))
    op.add_column("User", sa.Column("job", sa.String(length=255), nullable=True))
    op.add_column(
        "User",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            nullable=True,
            server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        ),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "gender")
    op.drop_column("User", "birth")
    op.drop_column("User", "location")
    op.drop_column("User", "job")
    # ### end Alembic commands ###
